{
    "version": "1.1.291",
    "time": "1674619057089",
    "generalDiagnostics": [
        {
            "file": "/workspace/src/pynchon/__init__.py",
            "severity": "error",
            "message": "Import \"click\" could not be resolved",
            "range": {
                "start": {
                    "line": 8,
                    "character": 7
                },
                "end": {
                    "line": 8,
                    "character": 12
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/__init__.py",
            "severity": "error",
            "message": "Import \"jinja2\" could not be resolved",
            "range": {
                "start": {
                    "line": 9,
                    "character": 7
                },
                "end": {
                    "line": 9,
                    "character": 13
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/__init__.py",
            "severity": "error",
            "message": "Import \"._version\" could not be resolved",
            "range": {
                "start": {
                    "line": 15,
                    "character": 9
                },
                "end": {
                    "line": 15,
                    "character": 18
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/__init__.py",
            "severity": "error",
            "message": "Import \"coloredlogs\" could not be resolved",
            "range": {
                "start": {
                    "line": 44,
                    "character": 15
                },
                "end": {
                    "line": 44,
                    "character": 26
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/annotate.py",
            "severity": "error",
            "message": "Argument of type \"list[Unknown] | Literal[0]\" cannot be assigned to parameter \"mccabe\" of type \"str | list[Unknown]\" in function \"update\"\n  Type \"list[Unknown] | Literal[0]\" cannot be assigned to type \"str | list[Unknown]\"\n    Type \"Literal[0]\" cannot be assigned to type \"str | list[Unknown]\"\n      \"Literal[0]\" is incompatible with \"str\"\n      \"Literal[0]\" is incompatible with \"list[Unknown]\"",
            "range": {
                "start": {
                    "line": 70,
                    "character": 32
                },
                "end": {
                    "line": 70,
                    "character": 68
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/annotate.py",
            "severity": "warning",
            "message": "Expression value is unused",
            "range": {
                "start": {
                    "line": 119,
                    "character": 4
                },
                "end": {
                    "line": 119,
                    "character": 82
                }
            },
            "rule": "reportUnusedExpression"
        },
        {
            "file": "/workspace/src/pynchon/config.py",
            "severity": "error",
            "message": "Function with declared type of \"dict[Unknown, Unknown]\" must return value on all code paths\n  Type \"None\" cannot be assigned to type \"dict[Unknown, Unknown]\"",
            "range": {
                "start": {
                    "line": 4,
                    "character": 54
                },
                "end": {
                    "line": 4,
                    "character": 58
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/config.py",
            "severity": "error",
            "message": "Function with declared type of \"dict[Unknown, Unknown]\" must return value on all code paths\n  Type \"None\" cannot be assigned to type \"dict[Unknown, Unknown]\"",
            "range": {
                "start": {
                    "line": 8,
                    "character": 23
                },
                "end": {
                    "line": 8,
                    "character": 27
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Import \"mccabe\" could not be resolved",
            "range": {
                "start": {
                    "line": 9,
                    "character": 7
                },
                "end": {
                    "line": 9,
                    "character": 13
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Import \"griffe\" could not be resolved",
            "range": {
                "start": {
                    "line": 10,
                    "character": 7
                },
                "end": {
                    "line": 10,
                    "character": 13
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Import \"tomli\" could not be resolved",
            "range": {
                "start": {
                    "line": 11,
                    "character": 7
                },
                "end": {
                    "line": 11,
                    "character": 12
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Import \"IPython\" could not be resolved",
            "range": {
                "start": {
                    "line": 26,
                    "character": 11
                },
                "end": {
                    "line": 26,
                    "character": 18
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Import \"click.core\" could not be resolved",
            "range": {
                "start": {
                    "line": 143,
                    "character": 9
                },
                "end": {
                    "line": 143,
                    "character": 19
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Expression of type \"None\" cannot be assigned to parameter of type \"str\"\n  Type \"None\" cannot be assigned to type \"str\"",
            "range": {
                "start": {
                    "line": 284,
                    "character": 27
                },
                "end": {
                    "line": 284,
                    "character": 31
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Expression of type \"None\" cannot be assigned to parameter of type \"str\"\n  Type \"None\" cannot be assigned to type \"str\"",
            "range": {
                "start": {
                    "line": 284,
                    "character": 46
                },
                "end": {
                    "line": 284,
                    "character": 50
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "warning",
            "message": "Import \"termcolor\" could not be resolved from source",
            "range": {
                "start": {
                    "line": 8,
                    "character": 7
                },
                "end": {
                    "line": 8,
                    "character": 16
                }
            },
            "rule": "reportMissingModuleSource"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Argument of type \"tuple[list[str]]\" cannot be assigned to parameter \"__main__\" of type \"str\" in function \"update\"\n  \"tuple[list[str]]\" is incompatible with \"str\"",
            "range": {
                "start": {
                    "line": 53,
                    "character": 41
                },
                "end": {
                    "line": 53,
                    "character": 49
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Argument of type \"Unknown | None\" cannot be assigned to parameter \"args\" of type \"_CMD\" in function \"__init__\"\n  Type \"Unknown | None\" cannot be assigned to type \"_CMD\"\n    Type \"None\" cannot be assigned to type \"_CMD\"\n      Type \"None\" cannot be assigned to type \"str\"\n      Type \"None\" cannot be assigned to type \"bytes\"\n      Type \"None\" cannot be assigned to type \"Sequence[StrOrBytesPath]\"",
            "range": {
                "start": {
                    "line": 355,
                    "character": 36
                },
                "end": {
                    "line": 355,
                    "character": 39
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Argument of type \"Unknown | None\" cannot be assigned to parameter \"args\" of type \"_CMD\" in function \"__init__\"\n  Type \"Unknown | None\" cannot be assigned to type \"_CMD\"\n    Type \"None\" cannot be assigned to type \"_CMD\"\n      Type \"None\" cannot be assigned to type \"str\"\n      Type \"None\" cannot be assigned to type \"bytes\"\n      Type \"None\" cannot be assigned to type \"Sequence[StrOrBytesPath]\"",
            "range": {
                "start": {
                    "line": 365,
                    "character": 36
                },
                "end": {
                    "line": 365,
                    "character": 39
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "\"write\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 356,
                    "character": 23
                },
                "end": {
                    "line": 356,
                    "character": 28
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "\"close\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 357,
                    "character": 23
                },
                "end": {
                    "line": 357,
                    "character": 28
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot access member \"succeeded\" for type \"Type[InvocationResult]\"\n  Member \"succeeded\" is unknown",
            "range": {
                "start": {
                    "line": 60,
                    "character": 15
                },
                "end": {
                    "line": 60,
                    "character": 24
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot access member \"succeeded\" for type \"Popen[Unknown]\"\n  Member \"succeeded\" is unknown",
            "range": {
                "start": {
                    "line": 60,
                    "character": 15
                },
                "end": {
                    "line": 60,
                    "character": 24
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot access member \"stdout\" for type \"Type[InvocationResult]\"\n  Member \"stdout\" is unknown",
            "range": {
                "start": {
                    "line": 60,
                    "character": 33
                },
                "end": {
                    "line": 60,
                    "character": 39
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot access member \"strip\" for type \"IO[Unknown]\"\n  Member \"strip\" is unknown",
            "range": {
                "start": {
                    "line": 60,
                    "character": 40
                },
                "end": {
                    "line": 60,
                    "character": 45
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "\"strip\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 60,
                    "character": 40
                },
                "end": {
                    "line": 60,
                    "character": 45
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "\"__version__\" is unknown import symbol",
            "range": {
                "start": {
                    "line": 65,
                    "character": 24
                },
                "end": {
                    "line": 65,
                    "character": 35
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Expression of type \"None\" cannot be assigned to return type \"str\"\n  Type \"None\" cannot be assigned to type \"str\"",
            "range": {
                "start": {
                    "line": 80,
                    "character": 15
                },
                "end": {
                    "line": 80,
                    "character": 19
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot access member \"succeeded\" for type \"Type[InvocationResult]\"\n  Member \"succeeded\" is unknown",
            "range": {
                "start": {
                    "line": 88,
                    "character": 15
                },
                "end": {
                    "line": 88,
                    "character": 24
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot access member \"succeeded\" for type \"Popen[Unknown]\"\n  Member \"succeeded\" is unknown",
            "range": {
                "start": {
                    "line": 88,
                    "character": 15
                },
                "end": {
                    "line": 88,
                    "character": 24
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot access member \"stdout\" for type \"Type[InvocationResult]\"\n  Member \"stdout\" is unknown",
            "range": {
                "start": {
                    "line": 88,
                    "character": 33
                },
                "end": {
                    "line": 88,
                    "character": 39
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot access member \"strip\" for type \"IO[Unknown]\"\n  Member \"strip\" is unknown",
            "range": {
                "start": {
                    "line": 88,
                    "character": 40
                },
                "end": {
                    "line": 88,
                    "character": 45
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "\"strip\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 88,
                    "character": 40
                },
                "end": {
                    "line": 88,
                    "character": 45
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Argument of type \"LiteralString | None\" cannot be assigned to parameter \"path\" of type \"StrPath\" in function \"relpath\"\n  Type \"LiteralString | None\" cannot be assigned to type \"StrPath\"\n    Type \"None\" cannot be assigned to type \"StrPath\"\n      Type \"None\" cannot be assigned to type \"str\"\n      \"__fspath__\" is not present",
            "range": {
                "start": {
                    "line": 97,
                    "character": 27
                },
                "end": {
                    "line": 97,
                    "character": 35
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Object of type \"None\" is not subscriptable",
            "range": {
                "start": {
                    "line": 120,
                    "character": 22
                },
                "end": {
                    "line": 120,
                    "character": 28
                }
            },
            "rule": "reportOptionalSubscript"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Object of type \"None\" is not subscriptable",
            "range": {
                "start": {
                    "line": 122,
                    "character": 14
                },
                "end": {
                    "line": 122,
                    "character": 20
                }
            },
            "rule": "reportOptionalSubscript"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "\"classes\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 194,
                    "character": 35
                },
                "end": {
                    "line": 194,
                    "character": 42
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "\"classes\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 195,
                    "character": 30
                },
                "end": {
                    "line": 195,
                    "character": 37
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "\"modules\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 201,
                    "character": 35
                },
                "end": {
                    "line": 201,
                    "character": 42
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "\"modules\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 202,
                    "character": 30
                },
                "end": {
                    "line": 202,
                    "character": 37
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "\"functions\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 208,
                    "character": 42
                },
                "end": {
                    "line": 208,
                    "character": 51
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "\"functions\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 209,
                    "character": 30
                },
                "end": {
                    "line": 209,
                    "character": 39
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Argument of type \"Unknown | None\" cannot be assigned to parameter \"text\" of type \"str\" in function \"colored\"\n  Type \"Unknown | None\" cannot be assigned to type \"str\"\n    Type \"None\" cannot be assigned to type \"str\"",
            "range": {
                "start": {
                    "line": 333,
                    "character": 38
                },
                "end": {
                    "line": 333,
                    "character": 41
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "warning",
            "message": "Expression value is unused",
            "range": {
                "start": {
                    "line": 331,
                    "character": 4
                },
                "end": {
                    "line": 335,
                    "character": 5
                }
            },
            "rule": "reportUnusedExpression"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Argument of type \"Unknown | None\" cannot be assigned to parameter \"command\" of type \"StrOrBytesPath\" in function \"system\"\n  Type \"Unknown | None\" cannot be assigned to type \"StrOrBytesPath\"\n    Type \"None\" cannot be assigned to type \"StrOrBytesPath\"\n      Type \"None\" cannot be assigned to type \"str\"\n      Type \"None\" cannot be assigned to type \"bytes\"\n      \"__fspath__\" is not present\n      \"__fspath__\" is not present",
            "range": {
                "start": {
                    "line": 338,
                    "character": 26
                },
                "end": {
                    "line": 338,
                    "character": 29
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot assign member \"failed\" for type \"Type[InvocationResult]\"\n  Member \"failed\" is unknown",
            "range": {
                "start": {
                    "line": 342,
                    "character": 15
                },
                "end": {
                    "line": 342,
                    "character": 21
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot assign member \"failure\" for type \"Type[InvocationResult]\"\n  Member \"failure\" is unknown",
            "range": {
                "start": {
                    "line": 342,
                    "character": 31
                },
                "end": {
                    "line": 342,
                    "character": 38
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot assign member \"success\" for type \"Type[InvocationResult]\"\n  Member \"success\" is unknown",
            "range": {
                "start": {
                    "line": 343,
                    "character": 15
                },
                "end": {
                    "line": 343,
                    "character": 22
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot assign member \"succeeded\" for type \"Type[InvocationResult]\"\n  Member \"succeeded\" is unknown",
            "range": {
                "start": {
                    "line": 343,
                    "character": 32
                },
                "end": {
                    "line": 343,
                    "character": 41
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot assign member \"stdout\" for type \"Type[InvocationResult]\"\n  Member \"stdout\" is unknown",
            "range": {
                "start": {
                    "line": 344,
                    "character": 15
                },
                "end": {
                    "line": 344,
                    "character": 21
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot assign member \"stdin\" for type \"Type[InvocationResult]\"\n  Member \"stdin\" is unknown",
            "range": {
                "start": {
                    "line": 344,
                    "character": 31
                },
                "end": {
                    "line": 344,
                    "character": 36
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "warning",
            "message": "Expression value is unused",
            "range": {
                "start": {
                    "line": 351,
                    "character": 8
                },
                "end": {
                    "line": 351,
                    "character": 57
                }
            },
            "rule": "reportUnusedExpression"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Argument of type \"int\" cannot be assigned to parameter \"stdin\" of type \"bool | dict[str | Unknown, str | Unknown]\" in function \"update\"\n  Type \"int\" cannot be assigned to type \"bool | dict[str | Unknown, str | Unknown]\"\n    \"int\" is incompatible with \"bool\"\n    \"int\" is incompatible with \"dict[str | Unknown, str | Unknown]\"",
            "range": {
                "start": {
                    "line": 353,
                    "character": 18
                },
                "end": {
                    "line": 353,
                    "character": 33
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Argument of type \"int\" cannot be assigned to parameter \"stdout\" of type \"bool | dict[str | Unknown, str | Unknown]\" in function \"update\"\n  Type \"int\" cannot be assigned to type \"bool | dict[str | Unknown, str | Unknown]\"\n    \"int\" is incompatible with \"bool\"\n    \"int\" is incompatible with \"dict[str | Unknown, str | Unknown]\"",
            "range": {
                "start": {
                    "line": 353,
                    "character": 42
                },
                "end": {
                    "line": 353,
                    "character": 57
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Argument of type \"int\" cannot be assigned to parameter \"stderr\" of type \"bool | dict[str | Unknown, str | Unknown]\" in function \"update\"\n  Type \"int\" cannot be assigned to type \"bool | dict[str | Unknown, str | Unknown]\"\n    \"int\" is incompatible with \"bool\"\n    \"int\" is incompatible with \"dict[str | Unknown, str | Unknown]\"",
            "range": {
                "start": {
                    "line": 353,
                    "character": 66
                },
                "end": {
                    "line": 353,
                    "character": 81
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Argument of type \"int\" cannot be assigned to parameter \"stdout\" of type \"bool | dict[str | Unknown, str | Unknown]\" in function \"update\"\n  Type \"int\" cannot be assigned to type \"bool | dict[str | Unknown, str | Unknown]\"\n    \"int\" is incompatible with \"bool\"\n    \"int\" is incompatible with \"dict[str | Unknown, str | Unknown]\"",
            "range": {
                "start": {
                    "line": 362,
                    "character": 23
                },
                "end": {
                    "line": 362,
                    "character": 38
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot assign member \"stdout\" for type \"Popen[Unknown]\"\n  Type \"Unknown | Literal['<LargeOutput>']\" cannot be assigned to type \"IO[Unknown] | None\"\n    Type \"Literal['<LargeOutput>']\" cannot be assigned to type \"IO[Unknown] | None\"\n      \"Literal['<LargeOutput>']\" is incompatible with \"IO[Unknown]\"\n      Type cannot be assigned to type \"None\"",
            "range": {
                "start": {
                    "line": 368,
                    "character": 26
                },
                "end": {
                    "line": 370,
                    "character": 9
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot assign member \"stdout\" for type \"Popen[Unknown]\"\n  Type \"Literal['<Interactive>']\" cannot be assigned to type \"IO[Unknown] | None\"\n    \"Literal['<Interactive>']\" is incompatible with \"IO[Unknown]\"\n    Type cannot be assigned to type \"None\"",
            "range": {
                "start": {
                    "line": 372,
                    "character": 26
                },
                "end": {
                    "line": 372,
                    "character": 41
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot assign member \"failed\" for type \"Popen[Unknown]\"\n  Member \"failed\" is unknown",
            "range": {
                "start": {
                    "line": 375,
                    "character": 13
                },
                "end": {
                    "line": 375,
                    "character": 19
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot access member \"failed\" for type \"Popen[Unknown]\"\n  Member \"failed\" is unknown",
            "range": {
                "start": {
                    "line": 376,
                    "character": 38
                },
                "end": {
                    "line": 376,
                    "character": 44
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot assign member \"succeeded\" for type \"Popen[Unknown]\"\n  Member \"succeeded\" is unknown",
            "range": {
                "start": {
                    "line": 376,
                    "character": 13
                },
                "end": {
                    "line": 376,
                    "character": 22
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot access member \"succeeded\" for type \"Popen[Unknown]\"\n  Member \"succeeded\" is unknown",
            "range": {
                "start": {
                    "line": 377,
                    "character": 32
                },
                "end": {
                    "line": 377,
                    "character": 41
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot assign member \"success\" for type \"Popen[Unknown]\"\n  Member \"success\" is unknown",
            "range": {
                "start": {
                    "line": 377,
                    "character": 13
                },
                "end": {
                    "line": 377,
                    "character": 20
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot access member \"failed\" for type \"Popen[Unknown]\"\n  Member \"failed\" is unknown",
            "range": {
                "start": {
                    "line": 378,
                    "character": 32
                },
                "end": {
                    "line": 378,
                    "character": 38
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/util.py",
            "severity": "error",
            "message": "Cannot assign member \"failure\" for type \"Popen[Unknown]\"\n  Member \"failure\" is unknown",
            "range": {
                "start": {
                    "line": 378,
                    "character": 13
                },
                "end": {
                    "line": 378,
                    "character": 20
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/api/render.py",
            "severity": "error",
            "message": "Import \"pyjson5\" could not be resolved",
            "range": {
                "start": {
                    "line": 3,
                    "character": 7
                },
                "end": {
                    "line": 3,
                    "character": 14
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/api/render.py",
            "severity": "error",
            "message": "Import \"jinja2\" could not be resolved",
            "range": {
                "start": {
                    "line": 5,
                    "character": 5
                },
                "end": {
                    "line": 5,
                    "character": 11
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/api/render.py",
            "severity": "warning",
            "message": "Operation on \"__all__\" is not supported, so exported symbol list may be incorrect",
            "range": {
                "start": {
                    "line": 105,
                    "character": 0
                },
                "end": {
                    "line": 105,
                    "character": 20
                }
            },
            "rule": "reportUnsupportedDunderAll"
        },
        {
            "file": "/workspace/src/pynchon/bin/api.py",
            "severity": "error",
            "message": "Import \"click\" could not be resolved",
            "range": {
                "start": {
                    "line": 2,
                    "character": 7
                },
                "end": {
                    "line": 2,
                    "character": 12
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/bin/cli.py",
            "severity": "error",
            "message": "Import \"click\" could not be resolved",
            "range": {
                "start": {
                    "line": 4,
                    "character": 7
                },
                "end": {
                    "line": 4,
                    "character": 12
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/bin/common.py",
            "severity": "error",
            "message": "Import \"click\" could not be resolved",
            "range": {
                "start": {
                    "line": 8,
                    "character": 7
                },
                "end": {
                    "line": 8,
                    "character": 12
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/bin/common.py",
            "severity": "error",
            "message": "Cannot access member \"handle\" for type \"handler\"\n  Member \"handle\" is unknown",
            "range": {
                "start": {
                    "line": 30,
                    "character": 20
                },
                "end": {
                    "line": 30,
                    "character": 26
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/bin/common.py",
            "severity": "warning",
            "message": "Instance methods should take a \"self\" parameter",
            "range": {
                "start": {
                    "line": 52,
                    "character": 14
                },
                "end": {
                    "line": 52,
                    "character": 15
                }
            },
            "rule": "reportSelfClsParameterName"
        },
        {
            "file": "/workspace/src/pynchon/bin/common.py",
            "severity": "error",
            "message": "Argument of type \"Unknown | None\" cannot be assigned to parameter \"file\" of type \"FileDescriptorOrPath\" in function \"open\"\n  Type \"Unknown | None\" cannot be assigned to type \"FileDescriptorOrPath\"\n    Type \"None\" cannot be assigned to type \"FileDescriptorOrPath\"\n      Type \"None\" cannot be assigned to type \"int\"\n      Type \"None\" cannot be assigned to type \"str\"\n      Type \"None\" cannot be assigned to type \"bytes\"\n      \"__fspath__\" is not present\n      \"__fspath__\" is not present",
            "range": {
                "start": {
                    "line": 60,
                    "character": 22
                },
                "end": {
                    "line": 60,
                    "character": 28
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/bin/common.py",
            "severity": "warning",
            "message": "Instance methods should take a \"self\" parameter",
            "range": {
                "start": {
                    "line": 71,
                    "character": 14
                },
                "end": {
                    "line": 71,
                    "character": 15
                }
            },
            "rule": "reportSelfClsParameterName"
        },
        {
            "file": "/workspace/src/pynchon/bin/common.py",
            "severity": "error",
            "message": "Expression of type \"None\" cannot be assigned to parameter of type \"str\"\n  Type \"None\" cannot be assigned to type \"str\"",
            "range": {
                "start": {
                    "line": 75,
                    "character": 46
                },
                "end": {
                    "line": 75,
                    "character": 50
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/bin/common.py",
            "severity": "error",
            "message": "\"formatters\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 80,
                    "character": 30
                },
                "end": {
                    "line": 80,
                    "character": 40
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/bin/common.py",
            "severity": "error",
            "message": "\"formatters\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 82,
                    "character": 30
                },
                "end": {
                    "line": 82,
                    "character": 40
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/bin/groups.py",
            "severity": "error",
            "message": "Import \"click\" could not be resolved",
            "range": {
                "start": {
                    "line": 3,
                    "character": 7
                },
                "end": {
                    "line": 3,
                    "character": 12
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/bin/groups.py",
            "severity": "error",
            "message": "\"group\" is not a known member of \"None\"",
            "range": {
                "start": {
                    "line": 18,
                    "character": 43
                },
                "end": {
                    "line": 18,
                    "character": 48
                }
            },
            "rule": "reportOptionalMemberAccess"
        },
        {
            "file": "/workspace/src/pynchon/bin/options.py",
            "severity": "error",
            "message": "Import \"click\" could not be resolved",
            "range": {
                "start": {
                    "line": 5,
                    "character": 7
                },
                "end": {
                    "line": 5,
                    "character": 12
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/bin/project.py",
            "severity": "error",
            "message": "Expression of type \"tuple[dict[Unknown, Unknown], list[Unknown]]\" cannot be assigned to return type \"dict[Unknown, Unknown]\"\n  \"tuple[dict[Unknown, Unknown], list[Unknown]]\" is incompatible with \"dict[Unknown, Unknown]\"",
            "range": {
                "start": {
                    "line": 105,
                    "character": 11
                },
                "end": {
                    "line": 105,
                    "character": 23
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/bin/render.py",
            "severity": "error",
            "message": "Import \"click\" could not be resolved",
            "range": {
                "start": {
                    "line": 12,
                    "character": 7
                },
                "end": {
                    "line": 12,
                    "character": 12
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/bin/render.py",
            "severity": "error",
            "message": "Import \"pyjson5\" could not be resolved",
            "range": {
                "start": {
                    "line": 15,
                    "character": 7
                },
                "end": {
                    "line": 15,
                    "character": 14
                }
            },
            "rule": "reportMissingImports"
        },
        {
            "file": "/workspace/src/pynchon/bin/render.py",
            "severity": "warning",
            "message": "Import \"yaml\" could not be resolved from source",
            "range": {
                "start": {
                    "line": 4,
                    "character": 7
                },
                "end": {
                    "line": 4,
                    "character": 11
                }
            },
            "rule": "reportMissingModuleSource"
        },
        {
            "file": "/workspace/src/pynchon/bin/render.py",
            "severity": "error",
            "message": "\"j5\" is not a known member of module",
            "range": {
                "start": {
                    "line": 52,
                    "character": 18
                },
                "end": {
                    "line": 52,
                    "character": 20
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/bin/render.py",
            "severity": "error",
            "message": "\"loads\" is not a known member of module",
            "range": {
                "start": {
                    "line": 120,
                    "character": 27
                },
                "end": {
                    "line": 120,
                    "character": 32
                }
            },
            "rule": "reportGeneralTypeIssues"
        },
        {
            "file": "/workspace/src/pynchon/bin/render.py",
            "severity": "error",
            "message": "\"j2\" is not a known member of module",
            "range": {
                "start": {
                    "line": 129,
                    "character": 19
                },
                "end": {
                    "line": 129,
                    "character": 21
                }
            },
            "rule": "reportGeneralTypeIssues"
        }
    ],
    "summary": {
        "filesAnalyzed": 16,
        "errorCount": 80,
        "warningCount": 8,
        "informationCount": 0,
        "timeInSec": 8.538
    }
}
